// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.27.1
// source: src/grpc/chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reponses formats
type ErrorCode int32

const (
	ErrorCode_UNKNOWN         ErrorCode = 0
	ErrorCode_INVALID_WITNESS ErrorCode = 1
	ErrorCode_INVALID_PUBKEY  ErrorCode = 2
	ErrorCode_INTERNAL_ERROR  ErrorCode = 3
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "INVALID_WITNESS",
		2: "INVALID_PUBKEY",
		3: "INTERNAL_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN":         0,
		"INVALID_WITNESS": 1,
		"INVALID_PUBKEY":  2,
		"INTERNAL_ERROR":  3,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_src_grpc_chat_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_src_grpc_chat_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_src_grpc_chat_proto_rawDescGZIP(), []int{0}
}

// Format of message used on the server side
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        []byte                 `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Witness       []byte                 `protobuf:"bytes,2,opt,name=witness,proto3" json:"witness,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_src_grpc_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_src_grpc_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *Message) GetWitness() []byte {
	if x != nil {
		return x.Witness
	}
	return nil
}

func (x *Message) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Message) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Requests formats
type GetMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesReq) Reset() {
	*x = GetMessagesReq{}
	mi := &file_src_grpc_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesReq) ProtoMessage() {}

func (x *GetMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesReq.ProtoReflect.Descriptor instead.
func (*GetMessagesReq) Descriptor() ([]byte, []int) {
	return file_src_grpc_chat_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessagesReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type PostMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrCode       ErrorCode              `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3,enum=chat.ErrorCode" json:"err_code,omitempty"`
	ErrMessage    string                 `protobuf:"bytes,3,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageResp) Reset() {
	*x = PostMessageResp{}
	mi := &file_src_grpc_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageResp) ProtoMessage() {}

func (x *PostMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageResp.ProtoReflect.Descriptor instead.
func (*PostMessageResp) Descriptor() ([]byte, []int) {
	return file_src_grpc_chat_proto_rawDescGZIP(), []int{2}
}

func (x *PostMessageResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PostMessageResp) GetErrCode() ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return ErrorCode_UNKNOWN
}

func (x *PostMessageResp) GetErrMessage() string {
	if x != nil {
		return x.ErrMessage
	}
	return ""
}

type GetMessagesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	ErrCode       ErrorCode              `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3,enum=chat.ErrorCode" json:"err_code,omitempty"`
	ErrMessage    string                 `protobuf:"bytes,3,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResp) Reset() {
	*x = GetMessagesResp{}
	mi := &file_src_grpc_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResp) ProtoMessage() {}

func (x *GetMessagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResp.ProtoReflect.Descriptor instead.
func (*GetMessagesResp) Descriptor() ([]byte, []int) {
	return file_src_grpc_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessagesResp) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResp) GetErrCode() ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return ErrorCode_UNKNOWN
}

func (x *GetMessagesResp) GetErrMessage() string {
	if x != nil {
		return x.ErrMessage
	}
	return ""
}

var File_src_grpc_chat_proto protoreflect.FileDescriptor

var file_src_grpc_chat_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22, 0x62, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x61, 0x67, 0x22, 0x78, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x2a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x65, 0x72, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x89, 0x01,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x29, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65,
	0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x55, 0x0a, 0x09, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x57,
	0x49, 0x54, 0x4e, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x50, 0x55, 0x42, 0x4b, 0x45, 0x59, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e,
	0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03,
	0x32, 0x83, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x33, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x12, 0x14, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x15, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_src_grpc_chat_proto_rawDescOnce sync.Once
	file_src_grpc_chat_proto_rawDescData []byte
)

func file_src_grpc_chat_proto_rawDescGZIP() []byte {
	file_src_grpc_chat_proto_rawDescOnce.Do(func() {
		file_src_grpc_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_grpc_chat_proto_rawDesc), len(file_src_grpc_chat_proto_rawDesc)))
	})
	return file_src_grpc_chat_proto_rawDescData
}

var file_src_grpc_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_grpc_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_src_grpc_chat_proto_goTypes = []any{
	(ErrorCode)(0),          // 0: chat.ErrorCode
	(*Message)(nil),         // 1: chat.Message
	(*GetMessagesReq)(nil),  // 2: chat.GetMessagesReq
	(*PostMessageResp)(nil), // 3: chat.PostMessageResp
	(*GetMessagesResp)(nil), // 4: chat.GetMessagesResp
}
var file_src_grpc_chat_proto_depIdxs = []int32{
	0, // 0: chat.PostMessageResp.err_code:type_name -> chat.ErrorCode
	1, // 1: chat.GetMessagesResp.messages:type_name -> chat.Message
	0, // 2: chat.GetMessagesResp.err_code:type_name -> chat.ErrorCode
	1, // 3: chat.ChatService.PostMessage:input_type -> chat.Message
	2, // 4: chat.ChatService.GetMessagesByTag:input_type -> chat.GetMessagesReq
	3, // 5: chat.ChatService.PostMessage:output_type -> chat.PostMessageResp
	4, // 6: chat.ChatService.GetMessagesByTag:output_type -> chat.GetMessagesResp
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_src_grpc_chat_proto_init() }
func file_src_grpc_chat_proto_init() {
	if File_src_grpc_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_grpc_chat_proto_rawDesc), len(file_src_grpc_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_grpc_chat_proto_goTypes,
		DependencyIndexes: file_src_grpc_chat_proto_depIdxs,
		EnumInfos:         file_src_grpc_chat_proto_enumTypes,
		MessageInfos:      file_src_grpc_chat_proto_msgTypes,
	}.Build()
	File_src_grpc_chat_proto = out.File
	file_src_grpc_chat_proto_goTypes = nil
	file_src_grpc_chat_proto_depIdxs = nil
}
